# Generated by Django 5.0.3 on 2024-03-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(max_length=10)),
                ('fruit_quan', models.IntegerField()),
                ('delivery_address', models.CharField(max_length=20)),
                ('delivery_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('ON', 'Online payment'), ('COD', 'Cash On delivery')], max_length=10)),
            ],
        ),
    ]
